### ISSUE TITLE
java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Property 'console' doesn't exist

### ISSUE THREAD

**Issue by leonardovargasleffa** [Traviskn/react-native-threads#161]
My development build is working fine. However, when I generate the production build, it throws the following error.

My worker is for Axios calls.

"react-native": "0.73.4",
"@exodus/react-native-threads": "^0.4.0",

12-12 18:27:36.520 16120 16194 E AndroidRuntime: FATAL EXCEPTION: mqt_js
12-12 18:27:36.520 16120 16194 E AndroidRuntime: Process: com.imonster.app PID: 16120
12-12 18:27:36.520 16120 16194 E AndroidRuntime: java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Property 'console' doesn't exist
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at com.facebook.react.bridge.DefaultJSExceptionHandler.handleException(DefaultJSExceptionHandler.java:20)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:195)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:614)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.-$$Nest$monNativeException(Unknown Source:0)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:632)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:40)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:211)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: Caused by: com.facebook.react.devsupport.JSException: Property 'console' doesn't exist
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at com.facebook.jni.NativeRunnable.run(Native Method)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
12-12 18:27:36.520 16120 16194 E AndroidRuntime: 	... 3 more

**Comment by leonardovargasleffa** [comment]
Resolved with console polyfill and 
global.__fbDisableExceptionsManager = true;
for production release
